### ISSUE TITLE
Stuck on "wait for terminal ramp" at Jeb's Junkyard

### ISSUE THREAD

**Issue by HiveHD** [caerfinon/KerbinSideRemasteredGAP#77]
This worked on previous missions fine but after landing at Jebs Junkyard for the first contract there, I am stuck waiting for terminal ramp. I got the notification for entering the terminal and it says I have successfully stopped (I can also recover the plane fine) but the ramp timer isn't triggering.

Have tried this with multiple different planes including the planes that worked for the previous missions. Any ideas? Is there a way to skip/ toggle the terminal steps?

![KSP_x64_z4lBX9pTGF](https://user-images.githubusercontent.com/10623760/227802568-c66111b9-ab25-4544-b3b3-bc298bf23b7a.png)

![KSP_x64_nSKihDFePh](https://user-images.githubusercontent.com/10623760/227802583-bc35f11a-fa3c-4d4a-8194-088b4ef4699f.jpg)

**Comment by caerfinon** [comment]
The Waypoint generator in Contract Configurator sometimes puts the waypoint in a vastly different spot. The Alt-F12 methos is the way to fix this particular glitch.
